name: "CI/CD: On core branch push"
on:
  push:
    branches:
      - main
      - develop
permissions:
      id-token: write       # Required for AWS OIDC connection
      contents: read        # Required by actions/checkout
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  terraform-apply-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra/prd/terraform
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Build Lambda function handler Go executable
        id: go-build
        working-directory: ./src
        run: GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o ../infra/prd/terraform/bin/bootstrap main.go

      - name: Assume CI AWS IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: terraform init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME_INFRA_PRD }}
          AWS_STATE_LOCK_TABLE_NAME: ${{ secrets.AWS_STATE_LOCK_TABLE_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="dynamodb_table=${AWS_STATE_LOCK_TABLE_NAME}"

      - name: terraform validate
        id: validate
        run: terraform validate

      - name: terraform plan
        id: plan
        env:
          TF_VAR_telegram_bot_token: ${{ secrets.TF_VAR_TELEGRAM_BOT_TOKEN }}
        run: terraform plan -input=false -out tf.plan -var="telegram_bot_token=${TF_VAR_telegram_bot_token}"

      - name: terraform apply
        id: apply
        if: ${{ steps.plan.outcome }} == 'success'
        run: terraform apply -auto-approve tf.plan

  terraform-apply-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ci/terraform
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Assume CI AWS IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: terraform init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME_CI }}
          AWS_STATE_LOCK_TABLE_NAME: ${{ secrets.AWS_STATE_LOCK_TABLE_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="dynamodb_table=${AWS_STATE_LOCK_TABLE_NAME}"

      - name: terraform validate
        id: validate
        run: terraform validate

      - name: terraform plan
        id: plan
        run: terraform plan -input=false -out tf.plan

      - name: terraform apply
        id: apply
        if: ${{ steps.plan.outcome }} == 'success'
        run: terraform apply -auto-approve tf.plan

